import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
const source=new URL('../app/AnalysisComparison.tsx',import.meta.url);
const compiled=ts.transpileModule(fs.readFileSync(source,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
const mod={exports:{}};new Function('module','exports','require',compiled)(mod,mod.exports,createRequire(source));
const {compareAnalysis,AnalysisComparison}=mod.exports;
const base={symbol:'AAA',methodVersion:'2',fetchedAt:'2026-09-13T03:00:00Z',status:'WAIT',financials:{fiscalDate:'2025-12-31'},fundamentals:{checks:[{key:'x',label:'成長',value:.1,status:'fail',detail:'15%'}]},technical:{checks:[{key:'x',label:'均線',value:100,status:'pass'}]},entry:{confirmation:[]}};
assert.equal(compareAnalysis(base,base).differences.length,0);
const after=structuredClone(base);after.fundamentals.checks[0].status='pass';after.fundamentals.checks[0].value=.2;after.financials.fiscalDate='2026-12-31';
assert.equal(compareAnalysis(base,after).differences.length,1);assert.equal(compareAnalysis(base,after).periodChanged,true);
assert.equal(compareAnalysis(base,{...after,methodVersion:'3'}),null);
assert.equal(compareAnalysis(base,{...after,symbol:'BBB'}),null);
assert.equal(compareAnalysis({...base,fetchedAt:'2026-09-14T00:00:00Z'},after).newerScan,true);
const removed=structuredClone(base);removed.technical.checks=[];assert.equal(compareAnalysis(base,removed).differences.length,1);
const html=renderToStaticMarkup(React.createElement(AnalysisComparison,{scan:base,current:after}));assert.match(html,/財報期間不同/);assert.match(html,/1 條條件有差異/);assert.match(html,/不寫入每日變化/);
console.log('Analysis comparison tests passed');

const {changeKind,comparisonValue}=mod.exports;
assert.equal(changeKind({status:'fail'},{status:'pass'}),'gained');
assert.equal(changeKind({status:'pass'},{status:'fail'}),'lost');
assert.equal(changeKind({status:'missing'},{status:'pass'}),'data');
assert.equal(changeKind({status:'pass'},{status:'missing'}),'data');
assert.equal(changeKind(null,{status:'pass'}),'data');
assert.equal(changeKind({status:'fail',detail:'old'},{status:'pass',detail:'new'}),'rule');
assert.equal(changeKind({status:'pass',value:1},{status:'pass',value:2}),'value');
assert.equal(comparisonValue({key:'growth',status:'pass',value:.15}),'15%');
assert.equal(comparisonValue({key:'volume',status:'pass',value:1.2}),'1.2 倍');
assert.equal(comparisonValue({key:'ocf',status:'pass',value:100},'EUR'),'100 EUR');
assert.match(comparisonValue({key:'ocf',status:'pass',value:100}),/幣別未知/);
assert.equal(comparisonValue({key:'reclaim',status:'pass',value:100}),'100 USD');
assert.equal(comparisonValue({key:'margin',status:'missing',value:null}),'資料不足');
assert.match(html,/新符合/);
console.log('Comparison categories and units passed');

const {entryComparison}=mod.exports;
assert.equal(entryComparison({},{}).filter(r=>r.changed).length,0);
const levels=entryComparison({zoneLow:100,zoneHigh:110,distance:0,riskReward:2},{zoneLow:105,zoneHigh:110,distance:.02,riskReward:null});
assert.equal(levels.find(r=>r.key==='zoneLow').change,'上調');
assert.equal(levels.find(r=>r.key==='zoneHigh').changed,false);
assert.equal(levels.find(r=>r.key==='distance').before,'0 %');
assert.equal(levels.find(r=>r.key==='distance').after,'2 %');
assert.equal(levels.find(r=>r.key==='riskReward').change,'暫無數值');
assert.equal(entryComparison({}, {riskReward:0}).find(r=>r.key==='riskReward').after,'0 : 1');
assert.equal(entryComparison({zoneLow:100},{zoneLow:100+1e-10})[0].changed,false);
assert.equal(entryComparison({zoneLow:NaN},{zoneLow:null})[0].changed,false);
const entryHtml=renderToStaticMarkup(React.createElement(AnalysisComparison,{scan:base,current:{...base,entry:{zoneLow:100},status:'QUALITY',dualPass:true}}));
assert.match(entryHtml,/1 項觀察數值變動/);
assert.match(entryHtml,/基本面＋技術面皆符合 · 等待回撤/);
assert.match(entryHtml,/無法估算/);
console.log('Entry comparison: missing data, zero, precision and status labels passed');
